/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdukterRouteImport } from './routes/produkter'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as BegagnatRouteImport } from './routes/begagnat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduktHandleRouteImport } from './routes/produkt.$handle'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterRoute = ProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const BegagnatRoute = BegagnatRouteImport.update({
  id: '/begagnat',
  path: '/begagnat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktHandleRoute = ProduktHandleRouteImport.update({
  id: '/produkt/$handle',
  path: '/produkt/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/begagnat': typeof BegagnatRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$handle': typeof ProduktHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/begagnat': typeof BegagnatRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$handle': typeof ProduktHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/begagnat': typeof BegagnatRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$handle': typeof ProduktHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/begagnat'
    | '/om-oss'
    | '/produkter'
    | '/sitemap.xml'
    | '/kategori/$slug'
    | '/produkt/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/begagnat'
    | '/om-oss'
    | '/produkter'
    | '/sitemap.xml'
    | '/kategori/$slug'
    | '/produkt/$handle'
  id:
    | '__root__'
    | '/'
    | '/begagnat'
    | '/om-oss'
    | '/produkter'
    | '/sitemap.xml'
    | '/kategori/$slug'
    | '/produkt/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BegagnatRoute: typeof BegagnatRoute
  OmOssRoute: typeof OmOssRoute
  ProdukterRoute: typeof ProdukterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  ProduktHandleRoute: typeof ProduktHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter': {
      id: '/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof ProdukterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begagnat': {
      id: '/begagnat'
      path: '/begagnat'
      fullPath: '/begagnat'
      preLoaderRoute: typeof BegagnatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$handle': {
      id: '/produkt/$handle'
      path: '/produkt/$handle'
      fullPath: '/produkt/$handle'
      preLoaderRoute: typeof ProduktHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BegagnatRoute: BegagnatRoute,
  OmOssRoute: OmOssRoute,
  ProdukterRoute: ProdukterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  ProduktHandleRoute: ProduktHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
